name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ -v --tb=short

    - name: Test API health
      run: |
        uvicorn api.app:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl -f http://localhost:8000/docs || exit 1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run flake8
      run: |
        flake8 api/ --max-line-length=120 --ignore=E203,W503
      continue-on-error: true

    - name: Check code formatting with black
      run: |
        black --check api/
      continue-on-error: true

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t fake-data-api:latest .

    - name: Test Docker container
      run: |
        docker run -d -p 8000:8000 --name test-api fake-data-api:latest
        sleep 10
        curl -f http://localhost:8000/docs || exit 1
        docker stop test-api
